### PR TITLE
Some changes in comment in min class.

### PR DESCRIPTION
**Pull request by nastaran23000**
Some changes in comment in min class.

### CODE REVIEW

**Comment by nastaran23000** [comment]
Some changes in comment in min class.

**Comment by nastarandehnavi** [comment]
Some changes in comment in min class.

**Comment by qiaoqiaozou** [comment]
OK

**Review by qiaoqiaozou — APPROVED** [review]
OK

**Review by Charity-kabutbei — APPROVED** [review]
the dataexchange is ok

**Comment by nastaran23000** [comment]
Some changes in comment in min class.

**Review by nastaran23000 — COMMENTED** [review]
Some changes in comment in main class.

**Pull request closed without merging**
