### PR TITLE
Reapply .gitignore rules

### PR DESCRIPTION
**Pull request by qiaoqiaozou**

### CODE REVIEW

**Comment by LyanaPP** [comment]
Good

**Review by LyanaPP — COMMENTED** [review]
Good to check The ignore file

**Comment by nastarandehnavi** [comment]
Its ok thank you.

**Review by nastarandehnavi — APPROVED** [review]
Its ok  thank you .

**Comment by nastarandehnavi** [comment]
Its ok thank you

**Comment by nastarandehnavi** [comment]
Its ok thank you

**Comment by nastaran23000** [comment]
Its ok thank you

**Comment by nastaran23000** [comment]
thank you  it is great.

**Review by Charity-kabutbei — APPROVED** [review]
the ingore file is okey

**Comment by LyanaPP** [comment]
now seems everything perfect

**Pull request merged**
