### PR TITLE
Modify some codes 0412

### PR DESCRIPTION
**Pull request by LyanaPP**
modify again

### CODE REVIEW

**Comment by LyanaPP** [comment]
modify

**Comment by qiaoqiaozou** [comment]
OK

**Review by qiaoqiaozou — APPROVED** [review]
OK

**Review by qiaoqiaozou — APPROVED** [review]
Good

**Comment by nastaran23000** [comment]
Everything is ok .

**Review by nastaran23000 — APPROVED** [review]
every thing is ok.

**Comment by LyanaPP** [comment]
good

**Pull request merged**
