### PR TITLE
Merge pull request #7 from nastarandehnavi/main

### PR DESCRIPTION
**Pull request by nastaran23000**
some changes in main class.

### CODE REVIEW

**Comment by nastaran23000** [comment]
some changes in main class.

**Comment by Charity-kabutbei** [comment]
all codes are okey

**Review by Charity-kabutbei — APPROVED** [review]
all codes are working

**Comment by qiaoqiaozou** [comment]
ok

**Review by qiaoqiaozou — APPROVED** [review]
ok

**Pull request merged**
